[package]
name = "ising_monte_carlo"
version = "1.3.1"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
edition = "2018"

[features]
default = []
autocorrelations = ["rayon", "rustfft"]
tempering = ["itertools"]
parallel-tempering = ["rayon", "tempering"]

[dependencies]
num = "^0.2"
rand = {version = "^0.7", features = ["small_rng"]}
smallvec = "^1.4"
itertools = {version = "^0.9", optional = true}
rayon = {version = "^1.3", optional = true}
rustfft = {version = "^3.0", optional = true}