[package]
name = "ising_monte_carlo"
version = "1.2.0"
authors = ["sumnernh@gmail.com <sumnernh@gmail.com>"]
edition = "2018"

[features]
default = ["parallel-tempering"]
autocorrelations = ["rayon", "rustfft"]
tempering = ["itertools"]
parallel-tempering = ["rayon", "tempering"]

[dependencies]
num = "^0.2"
rayon = {version = "^1.3", optional = true}
rustfft = {version = "^3.0", optional = true}
itertools = {version = "^0.9", optional = true}

[dependencies.rand]
version = "^0.7"
features = ["small_rng"]

[dependencies.smallvec]
version = "^1.4"
features = ["specialization"]
