[package]
name = "ising_monte_carlo"
version = "1.5.0"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
edition = "2018"

[features]
default = []
autocorrelations = ["rayon", "rustfft"]
tempering = ["itertools"]
parallel-tempering = ["rayon", "tempering"]
heatbath = []
serialize = ["serde", "rand/serde1", "smallvec/serde"]

[dev-dependencies]
rand = {version = "^0.7", features = ["small_rng"]}
serde_json = "^1.0"
rand_isaac = {version = "^0.2", features = ["serde1"]}

[dependencies]
rand = "^0.7"
smallvec = "^1.4"
itertools = {version = "^0.9", optional = true}
rayon = {version = "^1.3", optional = true}
serde = {version = "^1.0", optional = true, features = ["derive"]}
rustfft = {version = "^3.0", optional = true}