[package]
name = "ising_monte_carlo"
version = "1.2.0"
authors = ["sumnernh@gmail.com <sumnernh@gmail.com>"]
edition = "2018"

[features]
default = []
autocorrelations = ["rayon", "rustfft"]
tempering = ["itertools"]
parallel-tempering = ["rayon", "tempering"]

[dependencies]
num = "^0.2"
rand = {version = "^0.7", features = ["small_rng"]}
smallvec = "^1.4"
rayon = {version = "^1.3", optional = true}
rustfft = {version = "^3.0", optional = true}
itertools = {version = "^0.9", optional = true}