[package]
name = "ising_monte_carlo"
version = "1.4.0"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
edition = "2018"

[features]
default = []
autocorrelations = ["rayon", "rustfft"]
tempering = ["itertools"]
parallel-tempering = ["rayon", "tempering"]
heatbath = []
serialization = ["serde", "smallvec/serde", "serde_cbor", "rand/serde1"]
rand-small-rng = ["rand/small_rng", "rand_isaac"]

[profile.test]
default = ["rand-small-rng"]

[dependencies]
rand = "^0.7"
smallvec = "^1.4"
itertools = {version = "^0.9", optional = true}
serde = {version = "^1.0", optional = true, features = ["derive"]}
serde_cbor = {version = "^0.11", optional = true}
rand_isaac = {version = "^0.2", optional = true, features=["serde1"]}
rayon = {version = "^1.3", optional = true}
rustfft = {version = "^3.0", optional = true}