[package]
name = "monte_carlo"
version = "0.1.0"
authors = ["sumnernh@gmail.com <sumnernh@gmail.com>"]
edition = "2018"

[dependencies]
num = "^0.2.0"
rand = "^0.7.2"
rayon = "^1.2.1"
rustfft = "^3.0"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies.smallvec]
version = "^1.4"
features = ["specialization"]